### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by craigmaloney** [rsayers/jskim1#1]
I'm trying to run this locally on my machine (Ubuntu12.04, Chrome / Firefox latest) and I'm getting the following error:

simulator.js:1429: Uncaught TypeError: Illegal invocation

If I run this from your site I'm not getting that error.

Wondering if I'm missing something?

(BTW: Thanks for an awesome emulator!)

**Comment by rsayers** [comment]
Thanks for the heads up, I ended up getting the same error.  I did a quick fix just to get it going.  Should be working now.

**Comment by craigmaloney** [comment]
Works great. Thank you!
